### ISSUE TITLE
C# 10.0 值得補充的字串插補處理常式

### ISSUE THREAD

**Issue by mkjeff** [huanlin/LearningNotes#3]
C# 10.0對於字串插補提供了更細緻的控制方式，可以讓字串各式化更有效率，這是非常值得一提的新功能

https://docs.microsoft.com/zh-tw/dotnet/csharp/language-reference/proposals/csharp-10.0/improved-interpolated-strings#the-handler-pattern

**Comment by huanlin** [comment]
感謝建議! 已完成：[字串插補處理器](https://github.com/huanlin/LearningNotes/blob/main/csharp10/_post.md#%E5%AD%97%E4%B8%B2%E6%8F%92%E8%A3%9C%E8%99%95%E7%90%86%E5%99%A8)
